---
- name: Check Foreman is running
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - https://foreman.jamdoog.gra
        delay: 10
  rules:
    - name: Restart Foreman
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: Foreman Restart Gravelines
          organization: JamesGravelines
